Intentionally fail test to prove it works

diff --git a/.github/workflows/pr-test-and-build.yaml b/.github/workflows/pr-test-and-build.yaml
--- a/.github/workflows/pr-test-and-build.yaml
+++ b/.github/workflows/pr-test-and-build.yaml
@@ -97,10 +97,15 @@ jobs:
           sleep 5
           echo "Delete (restart) AGIMUS pod now that MySQL should be running and seeded..."
           kubectl --namespace agimus delete pod $(kubectl --namespace agimus get pods | grep agimus | awk '{print $1}') || true
-          echo "If after 20 seconds the string 'BOT IS ONLINE AND READY FOR COMMANDS' is not present in the logs, the test has failed"
+          echo "If after 20 seconds the string 'BOT IS ONLINE AND READY FOR COMMANDS' is not present in the logs, the test has failed..."
           sleep 20
-          kubectl --namespace agimus logs $(kubectl --namespace agimus get pods | grep agimus | awk '{print $1}') | grep "BOT IS ONLINE AND READY FOR COMMANDS"
-
+          if [[ -z "$(kubectl --namespace agimus logs $(kubectl --namespace agimus get pods | grep agimus | awk '{print $1}') | grep 'BOT IS ONLINE AND READY FOR COMMANDS')" ]]; then
+            echo "AGIMUS is online!!!"
+            exit 0
+          else
+            echo "AGIMUS is NOT online!!!"
+            exit 1
+          fi
           
       -
         name: Debug 
